import { useState } from "react";
import { Activity, Archive, Check, ChevronRight, CircleStop, FileCheck2, FileText, GitBranch, Pause, Play, RotateCcw, Send, ShieldAlert, ShieldCheck, SlidersHorizontal, Sparkles, Wrench } from "lucide-react";
import { Bar, Chip, Confirmed, EventRow, Label, Metric, Panel, Shell, Toggle } from "./_shared/Shell";
import "./_group.css";

export function ChiefAgent() {
  const [paused, setPaused] = useState(false);
  const [approved, setApproved] = useState(false);
  const [running, setRunning] = useState(false);
  const [showAudit, setShowAudit] = useState(false);
  const [request, setRequest] = useState("");
  const [budgetGate, setBudgetGate] = useState(true);

  const startRun = () => {
    setRunning(true);
    if (!request) setRequest("Shape the launch brief from the latest research");
  };

  return <Shell active="Chief agent" eyebrow="Orbit / supervisory desk" title="Chief agent">
    <div className="mb-7 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><Label>Orbit · human-in-the-loop</Label><h2 className="mt-2 text-4xl font-extrabold tracking-[-.07em]">See the whole thought.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--cyber-muted)]">Orbit turns a request into a bounded plan, names the workers, waits at approval gates, then leaves an artifact trail you can replay.</p></div><button onClick={() => setPaused(!paused)} className={`flex w-fit items-center gap-2 rounded-xl px-4 py-3 text-xs font-bold ${paused ? "bg-[var(--cyber-yellow)]" : "bg-[var(--cyber-ink)] text-[var(--cyber-paper)]"}`}>{paused ? <><Play size={14} /> Resume delegation</> : <><Pause size={14} /> Pause all delegation</>}</button></div>
    <Panel className="mb-5 overflow-hidden"><div className="flex flex-col gap-4 p-5 md:flex-row md:items-end"><div className="flex-1"><Label>new request → bounded run</Label><div className="mt-2 text-sm font-bold">What should Orbit coordinate?</div><input value={request} onChange={e => setRequest(e.target.value)} className="mt-3 w-full rounded-xl border border-[var(--cyber-line)] bg-[var(--cyber-paper)] px-4 py-3 text-sm outline-none focus:border-[#8e70d5]" placeholder="e.g. reconcile inventory and flag anything that needs my review" /></div><button onClick={startRun} className="flex items-center justify-center gap-2 rounded-xl bg-[var(--cyber-ink)] px-4 py-3 text-xs font-bold text-[var(--cyber-paper)]"><Send size={14} /> {running ? "Run active" : "Make a plan"}</button></div><div className="grid gap-2 border-t border-[var(--cyber-line)] bg-[var(--cyber-paper)] p-4 text-[10px] sm:grid-cols-3"><span><b>request</b> · {request ? "captured" : "waiting"}</span><span><b>workers</b> · Orbit will name eligible roles</span><span><b>approval</b> · external writes held</span></div></Panel>
    <div className="grid gap-5 xl:grid-cols-[1.18fr_.82fr]">
      <Panel className="p-5"><div className="flex items-center justify-between"><Label>task lineage · {running ? "live" : "replayable"}</Label><Chip tone={paused ? "yellow" : running ? "mint" : "lilac"}>{paused ? "paused" : running ? "running" : "ready"}</Chip></div><div className="mt-6 space-y-3"><div className="rounded-xl bg-[var(--cyber-lilac)] p-4"><div className="flex items-center gap-2 text-[12px] font-bold"><GitBranch size={15} /> Parent plan · {request || "Launch brief v3"}</div><div className="mt-2 text-[10px] text-[var(--cyber-muted)]">Orbit · created 14:08 · budget cap $18 · approval gates 2 · retry ceiling 2</div></div>{[["01", "Mica / source audit", "collect 6 cited sources", "active", "sky"], ["02", "Vale / structure draft", "waiting on source audit checkpoint", "waiting", "yellow"], ["03", "Nix / artifact assembler", "draft Markdown + frontmatter", "queued", "mint"], ["04", "Orbit / approval synthesis", "blocked by child tasks", "blocked", "pink"]].map(([n, a, b, s, tone]) => <div key={n} className="ml-5 flex items-center gap-3 border-l-2 border-[var(--cyber-line)] pl-4"><div className="grid h-8 w-8 place-items-center rounded-lg text-[10px] font-bold" style={{ background: `var(--cyber-${tone})` }}>{n}</div><div className="flex-1"><div className="text-[12px] font-bold">{a}</div><div className="text-[10px] text-[var(--cyber-muted)]">{b}</div></div><Chip tone={s === "active" ? "mint" : s === "blocked" ? "pink" : s === "waiting" ? "yellow" : "sky"}>{s}</Chip><ChevronRight size={14} /></div>)}</div><div className="mt-6 border-t border-[var(--cyber-line)] pt-5"><div className="flex items-center justify-between"><Label>delegation queue</Label><span className="mono text-[9px]">4 / 7 complete</span></div><div className="mt-3"><Bar value={57} color="#8e70d5" /></div><div className="mt-4 grid grid-cols-3 gap-2"><Metric value="2" label="retries left" tone="yellow" /><Metric value="$18" label="run budget cap" tone="mint" /><Metric value="2" label="gates pending" tone="pink" /></div></div></Panel>
      <div className="space-y-5"><Panel className="p-5"><div className="flex items-center justify-between"><Label>guardrails</Label><SlidersHorizontal size={15} /></div>{[["External writes", "approval required"], ["Max retries", "2 per task"], ["Run budget", "$18.00"], ["Human idle timeout", "15 minutes"]].map(([a, b], i) => <div key={a} className="flex justify-between border-b border-[var(--cyber-line)] py-3 text-[11px] last:border-0"><span>{a}</span><b className={i === 0 ? "text-[#a35d83]" : ""}>{b}</b></div>)}<div className="mt-4 flex items-center justify-between rounded-lg bg-[var(--cyber-paper)] p-3 text-[10px]"><span className="flex items-center gap-2"><RotateCcw size={13} /> stop when budget is reached</span><Toggle on={budgetGate} onToggle={() => setBudgetGate(!budgetGate)} label="Stop at budget limit" /></div><button className="mt-4 text-[11px] font-bold underline">Edit policy</button></Panel><Panel className="p-5"><Label>intervention queue</Label><div className="mt-4 flex gap-3"><ShieldAlert size={18} className="text-[#a35d83]" /><div className="flex-1"><div className="text-sm font-bold">Mica requests browser access</div><div className="mt-1 text-[10px] text-[var(--cyber-muted)]">Northstar · one session · read-only · expires in 18m</div><div className="mt-3 flex flex-wrap gap-2"><button onClick={() => setApproved(true)} className="rounded-lg bg-[var(--cyber-mint)] px-3 py-2 text-[10px] font-bold">{approved ? <Confirmed>Approved</Confirmed> : "Approve access"}</button><button onClick={() => setApproved(false)} className="rounded-lg border border-[var(--cyber-line)] px-3 py-2 text-[10px] font-bold"><CircleStop size={11} className="mr-1 inline" /> Deny</button></div></div></div></Panel></div>
    </div>
    <Panel className="mt-5 p-5"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><Label>event vocabulary · live audit</Label><div className="mt-1 text-sm font-bold">Every transition has a legible kind.</div></div><button onClick={() => setShowAudit(!showAudit)} className="flex items-center gap-1 text-[10px] font-bold underline">{showAudit ? "Hide full replay" : "Open full replay"} <Play size={12} /></button></div><div className="mt-4 grid gap-2 md:grid-cols-2">{[["model", "Orbit made a plan from the request", "R-240521-07 · 14:08:12", Sparkles, "lilac"], ["tool", "Mica opened a read-only browser session", "permission scope · expires in 18m", Wrench, "sky"], ["handoff", "Mica handed six citations to Vale", "checkpoint · 14:31:44", GitBranch, "mint"], ["guardrail", "Orbit paused the publish step", "external-write policy · 14:32:08", ShieldCheck, "pink"], ["artifact", "brief-v3.md draft is ready", "frontmatter preserved · 14:32:16", FileText, "yellow"], ["approval", "Ari approved one draft write", "human decision · waiting to apply", Check, "mint"]].map(([kind, title, meta, Icon, tone]) => <EventRow key={kind as string} icon={Icon as typeof Activity} title={title as string} meta={`${(kind as string).toUpperCase()} · ${meta as string}`} tone={tone as "lilac" | "sky" | "mint" | "pink" | "yellow"} active />)}</div>{showAudit && <div className="mt-4 rounded-xl bg-[var(--cyber-ink)] p-4 mono text-[9px] leading-5 text-[var(--cyber-paper)]"><div className="flex items-center gap-2 text-[var(--cyber-mint)]"><Archive size={13} /> REPLAY R-240521-07 · immutable event order</div><div className="mt-3 opacity-75">14:08:12 request accepted · 14:08:19 plan emitted · 14:09:02 Mica assigned<br />14:31:44 checkpoint stored · 14:32:08 guardrail pause · 14:32:16 artifact staged</div></div>}</Panel>
    <div className="mt-5 flex flex-wrap items-center gap-3 text-[10px] text-[var(--cyber-muted)]"><FileCheck2 size={14} /> Artifacts keep agent, run, project, and approval provenance.<span className="ml-auto flex items-center gap-2"><Activity size={13} /> {paused ? "Delegation paused safely" : "Audit stream recording"}</span></div>
  </Shell>;
}