import { useState } from "react";
import { ArrowUpRight, Check, CircleDot, FileText, GitBranch, Play, Send, ShieldCheck, Sparkles, Timer, Wand2 } from "lucide-react";
import { Bar, Chip, Confirmed, EventRow, Label, Metric, Panel, Shell, Toggle } from "./_shared/Shell";
import "./_group.css";

export function Home() {
  const [sent, setSent] = useState(false);
  const [approval, setApproval] = useState(false);
  const [showReplay, setShowReplay] = useState(false);
  const [guardrail, setGuardrail] = useState(true);

  return <Shell active="Home" eyebrow="Tuesday / 21 May 2024" title="Good morning, Ari">
    <div className="mb-8 flex flex-col justify-between gap-5 lg:flex-row lg:items-end">
      <div><Label>chief agent · Orbit online</Label><h2 className="mt-2 max-w-2xl text-[clamp(34px,5vw,62px)] font-extrabold leading-[.92] tracking-[-.08em]">Tell me what<br /><span className="text-[#8e70d5]">matters today.</span></h2><p className="mt-4 max-w-lg text-sm leading-6 text-[var(--cyber-muted)]">One calm conversation for the whole constellation. You approve the edges; Orbit carries the middle.</p></div>
      <button onClick={() => setSent(true)} className="flex w-fit items-center gap-2 rounded-xl bg-[var(--cyber-ink)] px-4 py-3 text-xs font-bold text-[var(--cyber-paper)]"><Wand2 size={15} /> {sent ? "Plan is ready" : "Start a plan"}</button>
    </div>

    <div className="grid gap-5 xl:grid-cols-[1.12fr_.88fr]">
      <Panel className="overflow-hidden">
        <div className="flex items-center justify-between border-b border-[var(--cyber-line)] p-5"><div className="flex items-center gap-2"><div className="grid h-8 w-8 place-items-center rounded-full bg-[var(--cyber-lilac)]"><Sparkles size={15} /></div><div><div className="text-sm font-bold">Orbit <span className="font-normal text-[var(--cyber-muted)]">/ chief agent</span></div><div className="mono text-[9px] text-[#57a57d]">ready · human approval on</div></div></div><Chip tone="mint">bounded mode</Chip></div>
        <div className="space-y-5 p-5"><div className="max-w-[90%] rounded-2xl rounded-tl-sm bg-[var(--cyber-paper)] p-4 text-sm leading-6">I found three useful threads for today: reconcile the inventory, shape the launch brief, and clean up 12 stale notes. Shall I make a plan that keeps the launch brief under review?</div><div className="ml-auto max-w-[90%] rounded-2xl rounded-tr-sm bg-[var(--cyber-lilac)] p-4 text-sm leading-6">Yes. Keep anything external behind an approval gate.</div>{sent && <div className="max-w-[90%] rounded-2xl rounded-tl-sm bg-[var(--cyber-paper)] p-4 text-sm leading-6">Done. I made a three-step plan with named workers, a $18 budget, two review gates, and a two-retry ceiling. Nothing will publish without you.</div>}<div className="flex gap-2 border-t border-[var(--cyber-line)] pt-4"><input aria-label="Ask Orbit" className="min-w-0 flex-1 rounded-xl border border-[var(--cyber-line)] bg-[var(--cyber-paper)] px-4 py-3 text-sm outline-none focus:border-[#8e70d5]" placeholder="Ask Orbit to coordinate something…" onKeyDown={e => { if (e.key === "Enter") setSent(true); }} /><button aria-label="Send request" onClick={() => setSent(true)} className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[var(--cyber-ink)] text-[var(--cyber-paper)]"><Send size={15} /></button></div></div>
      </Panel>

      <div className="space-y-5">
        <Panel className="p-5"><div className="flex items-center justify-between"><Label>today's pulse</Label><CircleDot size={14} className="text-[#57bd8b]" /></div><div className="mt-5 grid grid-cols-2 gap-3"><Metric value="28" label="agents in rhythm" tone="mint" /><Metric value="02" label="asks your eyes" tone="yellow" /></div><div className="mt-5"><div className="mb-2 flex justify-between text-[11px]"><span>compute window</span><b>62.4%</b></div><Bar value={62} color="#8e70d5" /></div><div className="mt-4 flex items-center justify-between border-t border-[var(--cyber-line)] pt-4 text-[10px]"><span className="flex items-center gap-2"><Timer size={13} /> budget remaining</span><b>$31.40 of $50</b></div></Panel>
        <Panel className="p-5"><Label>shared brain availability</Label><div className="mt-4 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[var(--cyber-pink)]"><GitBranch size={17} /></div><div className="flex-1"><div className="text-sm font-bold">Ari’s Obsidian vault</div><div className="mt-1 text-[10px] text-[var(--cyber-muted)]">1,842 notes · 9 agents indexing · global read/search</div></div><Chip tone="mint">online</Chip></div><div className="mt-4 rounded-xl bg-[var(--cyber-paper)] p-3 text-[10px] leading-5 text-[var(--cyber-muted)]"><b className="text-[var(--cyber-ink)]">Writes stay proposed.</b> Project overlays decide which folders an agent can see; frontmatter keeps provenance attached.</div></Panel>
      </div>
    </div>

    <div className="mt-5 grid gap-5 xl:grid-cols-[.9fr_1.1fr]">
      <Panel className="p-5"><div className="flex items-center justify-between"><Label>plan relay</Label><Chip tone="lilac">request → replay</Chip></div><div className="mt-5 space-y-3"><div className="rounded-xl bg-[var(--cyber-lilac)] p-4"><div className="flex items-center gap-2 text-[12px] font-bold"><GitBranch size={15} /> Launch brief v3</div><div className="mt-2 text-[10px] text-[var(--cyber-muted)]">Orbit · 3 workers · $18 cap · 2 retries per task</div></div>{[["01", "Mica", "source audit", "6 citations attached", "mint"], ["02", "Vale", "structure draft", "waiting on Mica", "yellow"], ["03", "Ari", "approval gate", "external write held", "pink"]].map(([num, agent, role, detail, tone]) => <div key={num} className="flex items-center gap-3 border-b border-[var(--cyber-line)] pb-3 last:border-0 last:pb-0"><div className="mono text-[9px] text-[var(--cyber-muted)]">{num}</div><div className="flex-1"><div className="text-[11px] font-bold">{agent} <span className="font-normal text-[var(--cyber-muted)]">· {role}</span></div><div className="mt-1 text-[10px] text-[var(--cyber-muted)]">{detail}</div></div><Chip tone={tone as "mint" | "yellow" | "pink"}>{tone === "mint" ? "done" : tone === "yellow" ? "checkpoint" : "approval"}</Chip></div>)}</div><button onClick={() => setShowReplay(!showReplay)} className="mt-4 flex items-center gap-2 text-[11px] font-bold text-[#7659bd]">{showReplay ? "Hide replay preview" : "Preview replay"} <Play size={12} /></button>{showReplay && <div className="mt-3 rounded-xl border border-dashed border-[#b9a7e9] bg-[#fbf9ff] p-3 mono text-[9px] leading-5 text-[var(--cyber-muted)]">R-240521-07 · request accepted 14:08<br />worker handoff Mica → Vale · checkpoint 14:31<br />approval held · artifact draft-brief-v3.md</div>}</Panel>
      <Panel className="p-5"><div className="flex items-center justify-between"><Label>approval pocket</Label><button onClick={() => setApproval(!approval)} className="text-[11px] font-bold text-[#7659bd]">{approval ? "Queue acknowledged" : "Open queue"} <ArrowUpRight size={13} className="inline" /></button></div><div className="mt-4 flex flex-col gap-3 md:flex-row md:items-center"><ShieldCheck size={20} className="text-[#7659bd]" /><div className="flex-1"><div className="text-sm font-bold">Allow brief-writer to write one draft to /launch/briefs?</div><div className="mt-1 text-[10px] text-[var(--cyber-muted)]">Proposed by Orbit · source: Vale · run R-240521-07 · expires in 42m · no publish access</div></div><button onClick={() => setApproval(true)} className="rounded-lg bg-[var(--cyber-mint)] px-4 py-2 text-[11px] font-bold">{approval ? <Confirmed>Approved once</Confirmed> : <><Check size={13} className="mr-1 inline" /> Approve once</>}</button></div><div className="mt-5 flex items-center justify-between border-t border-[var(--cyber-line)] pt-4"><div className="flex items-center gap-2 text-[10px] text-[var(--cyber-muted)]"><span>external writes</span><Toggle on={guardrail} onToggle={() => setGuardrail(!guardrail)} label="External writes approval gate" /></div><span className="mono text-[9px]">{guardrail ? "GATE ON" : "GATE OFF"}</span></div></Panel>
    </div>

    <Panel className="mt-5 p-5"><div className="flex items-center justify-between"><Label>event stream · human-readable</Label><button className="text-[10px] font-bold underline">View observability</button></div><div className="mt-4 grid gap-2 md:grid-cols-2">{[
      ["model", "Orbit made a plan from your request", "R-240521-07 · 14:08:12", "lilac"],
      ["handoff", "Mica handed six citations to Vale", "worker checkpoint · 14:31:44", "sky"],
      ["guardrail", "Publish step paused for approval", "policy / external-write · 14:32:08", "pink"],
      ["artifact", "brief-v3.md draft is ready to inspect", "frontmatter preserved · 14:32:16", "mint"],
    ].map(([kind, title, meta, tone]) => <EventRow key={kind} icon={kind === "model" ? Sparkles : kind === "handoff" ? GitBranch : kind === "guardrail" ? ShieldCheck : FileText} title={title} meta={`${kind.toUpperCase()} · ${meta}`} tone={tone as "lilac" | "sky" | "pink" | "mint"} active />)}</div></Panel>
  </Shell>;
}