import { useState } from "react";
import { Check, ChevronRight, FileCode2, FileText, GitBranch, Link2, LockKeyhole, RefreshCw, Search, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { Bar, Chip, Confirmed, Label, Metric, Panel, Shell, Toggle } from "./_shared/Shell";
import "./_group.css";

type Note = { title: string; path: string; excerpt: string; scope: string; agent: string };

export function MemoryWire() {
  const [connected, setConnected] = useState(true);
  const [approved, setApproved] = useState(false);
  const [conflictResolved, setConflictResolved] = useState(false);
  const [showBoundaries, setShowBoundaries] = useState(true);
  const [reindexed, setReindexed] = useState(false);
  const [query, setQuery] = useState("");
  const notes: Note[] = [
    { title: "Launch decision / April cohort", path: "/Projects/Northstar/brief.md", excerpt: "Shorter setup time is the strongest positioning signal.", scope: "Northstar overlay", agent: "Orbit · R-240521-07" },
    { title: "Research / competitor onboarding", path: "/Research/market/onboarding.md", excerpt: "Six cited sources mention setup friction in the first session.", scope: "global vault", agent: "Mica · R-240521-07" },
    { title: "Archive / old launch assumptions", path: "/Archive/launch-2023.md", excerpt: "Historical context, read-only for current project agents.", scope: "archive overlay", agent: "Ari · indexed" },
  ];
  const visibleNotes = notes.filter(note => `${note.title} ${note.path} ${note.excerpt}`.toLowerCase().includes(query.toLowerCase()));

  return <Shell active="Memory wire" eyebrow="shared brain / project overlays" title="Memory wire">
    <div className="mb-7 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><Label>Obsidian · shared second brain</Label><h2 className="mt-2 text-4xl font-extrabold tracking-[-.07em]">Make memory readable.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--cyber-muted)]">One common vault for the whole constellation. Projects layer scope and permissions on top; every proposed write keeps its provenance and can surface a conflict.</p></div><button onClick={() => setConnected(!connected)} className="flex w-fit items-center gap-2 rounded-xl border border-[var(--cyber-line)] bg-[var(--cyber-panel)] px-4 py-3 text-xs font-bold"><Link2 size={15} />{connected ? "Vault connected" : "Connect vault"}</button></div>
    <div className="grid gap-5 xl:grid-cols-[.82fr_1.18fr]">
      <div className="space-y-5">
        <Panel className="p-5"><div className="flex items-start justify-between"><div><Label>global vault status</Label><h3 className="mt-2 text-xl font-extrabold">Ari’s Obsidian vault</h3></div><Chip tone={connected ? "mint" : "pink"}>{connected ? "online" : "offline"}</Chip></div><div className="mt-5 grid grid-cols-2 gap-3"><Metric value="1,842" label="notes indexed" tone="lilac" /><Metric value="17" label="linked clusters" tone="sky" /></div><div className="mt-5 space-y-3 text-[11px]"><div className="flex justify-between border-b border-[var(--cyber-line)] pb-3"><span>global read + search</span><b className="text-[#4c9c76]">all agents</b></div><div className="flex justify-between border-b border-[var(--cyber-line)] pb-3"><span>proposed writes</span><b className="text-[#9b5e79]">review only</b></div><div className="flex justify-between border-b border-[var(--cyber-line)] pb-3"><span>index freshness</span><b>{reindexed ? "just now" : "2 min ago"}</b></div><div className="flex justify-between"><span>frontmatter</span><b className="text-[#4c9c76]">preserved</b></div></div><button onClick={() => setReindexed(true)} className="mt-5 text-[11px] font-bold underline"><RefreshCw size={12} className="mr-1 inline" /> {reindexed ? "Index refreshed" : "Re-index shared vault"}</button></Panel>
        <Panel className="p-5"><div className="flex items-center justify-between"><Label>project scope overlays</Label><SlidersHorizontal size={15} /></div><div className="mt-4 space-y-2">{[["Northstar launch", "/Projects/Northstar", "read + proposed write", "mint"], ["Quiet archive", "/Projects/Archive", "read only", "sky"], ["Q3 ledger", "/Projects/Ledger", "read + proposed write", "yellow"]].map(([project, path, access, tone]) => <div key={project} className="flex items-center gap-3 rounded-xl bg-[var(--cyber-paper)] p-3"><div className="h-2.5 w-2.5 rounded-full" style={{ background: `var(--cyber-${tone})` }} /><div className="flex-1"><div className="text-[11px] font-bold">{project}</div><div className="mono mt-1 text-[9px] text-[var(--cyber-muted)]">{path}</div></div><Chip tone={tone as "mint" | "sky" | "yellow"}>{access}</Chip></div>)}</div><div className="mt-4 flex items-center justify-between border-t border-[var(--cyber-line)] pt-4 text-[10px]"><span>show boundary labels in search</span><Toggle on={showBoundaries} onToggle={() => setShowBoundaries(!showBoundaries)} label="Show memory boundaries" /></div></Panel>
      </div>
      <Panel className="p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><Label>search the common brain</Label><div className="mt-1 text-sm font-bold">Every result explains its boundary.</div></div><div className="relative"><Search className="absolute left-3 top-2.5 text-[var(--cyber-muted)]" size={14} /><input aria-label="Search shared vault" value={query} onChange={e => setQuery(e.target.value)} className="w-full rounded-lg border border-[var(--cyber-line)] bg-[var(--cyber-paper)] py-2 pl-9 pr-3 text-[11px] outline-none focus:border-[#8e70d5] sm:w-64" placeholder="Search notes and paths…" /></div></div><div className="mt-5 space-y-2">{visibleNotes.map(note => <div key={note.title} className="rounded-xl border border-[var(--cyber-line)] p-4"><div className="flex items-start gap-3"><FileText size={17} className="mt-0.5 text-[#7659bd]" /><div className="min-w-0 flex-1"><div className="text-[12px] font-bold">{note.title}</div><div className="mono mt-1 truncate text-[9px] text-[var(--cyber-muted)]">{note.path}</div><p className="mt-3 text-[11px] leading-5 text-[var(--cyber-muted)]">{note.excerpt}</p><div className="mt-3 flex flex-wrap items-center gap-2"><Chip tone="sky">{showBoundaries ? note.scope : "scope hidden"}</Chip><span className="mono text-[9px] text-[var(--cyber-muted)]">{note.agent}</span></div></div><ChevronRight size={14} className="shrink-0 text-[var(--cyber-muted)]" /></div></div>)}{visibleNotes.length === 0 && <div className="rounded-xl bg-[var(--cyber-paper)] p-6 text-center text-[11px] text-[var(--cyber-muted)]">No notes in the shared index match that query.</div>}</div></Panel>
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
      <Panel className="p-5"><div className="flex items-center justify-between"><Label>proposed writes · 02</Label><Chip tone="pink">review queue</Chip></div><div className="mt-5 rounded-xl border border-[#d7c4d0] bg-[#fff7fb] p-4"><div className="flex items-start gap-3"><FileCode2 size={18} className="mt-1 text-[#a35d83]" /><div className="flex-1"><div className="text-sm font-bold">Add launch decision to project brief</div><div className="mt-1 mono text-[9px] text-[var(--cyber-muted)]">/Projects/Northstar/brief.md · frontmatter preserved</div><div className="mt-4 rounded-lg bg-[var(--cyber-panel)] p-3 text-[11px] leading-5"><b>proposed change</b><br />“Position the April cohort around shorter setup time.”<div className="mt-2 text-[10px] text-[var(--cyber-muted)]">agent: Orbit · run: R-240521-07 · project: Northstar · confidence: 0.91</div></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => setApproved(true)} className="rounded-lg bg-[var(--cyber-mint)] px-3 py-2 text-[11px] font-bold">{approved ? <Confirmed>Written to draft</Confirmed> : <><Check size={12} className="mr-1 inline" /> Approve draft write</>}</button><button onClick={() => setConflictResolved(!conflictResolved)} className="rounded-lg border border-[var(--cyber-line)] px-3 py-2 text-[11px] font-bold">{conflictResolved ? "Conflict marked resolved" : "Compare conflict"}</button></div>{conflictResolved && <div className="mt-3 rounded-lg bg-[var(--cyber-yellow)] p-3 text-[10px] leading-5"><b>Conflict surfaced.</b> The file changed after Orbit’s read. Review the current line before accepting the proposed hunk.</div>}</div></div></div><div className="mt-5 border-t border-[var(--cyber-line)] pt-5"><div className="flex items-center gap-3"><ShieldCheck size={18} className="text-[#4c9c76]" /><div><div className="text-sm font-bold">Provenance is attached</div><div className="text-[10px] text-[var(--cyber-muted)]">Agent, run, timestamp, project scope, and the original Markdown/frontmatter travel with every proposal.</div></div></div></div></Panel>
      <Panel className="p-5"><Label>permission membrane</Label><div className="mt-4 space-y-3"><div className="rounded-xl bg-[var(--cyber-mint)] p-4"><div className="flex items-center gap-2 text-[11px] font-bold"><Search size={14} /> read + search</div><p className="mt-2 text-[10px] leading-5">All agents can search the shared index. Results carry the project overlay and source path.</p></div><div className="rounded-xl bg-[var(--cyber-pink)] p-4"><div className="flex items-center gap-2 text-[11px] font-bold"><LockKeyhole size={14} /> proposed writes</div><p className="mt-2 text-[10px] leading-5">No silent mutations. A human reviews the exact Markdown diff, provenance, and conflicts.</p></div><div className="rounded-xl bg-[var(--cyber-paper)] p-4"><div className="flex items-center gap-2 text-[11px] font-bold"><GitBranch size={14} /> project overlay</div><p className="mt-2 text-[10px] leading-5">Northstar can scope /Projects/Northstar without turning the shared brain into a silo.</p></div></div></Panel>
    </div>
    <div className="mt-5 flex items-center gap-3 text-[10px] text-[var(--cyber-muted)]"><GitBranch size={14} /> {approved ? "1 proposal accepted into a draft; audit provenance retained." : "3 proposed writes are waiting for human review"}<div className="flex-1"><Bar value={approved ? 68 : 42} color="#8e70d5" /></div></div>
  </Shell>;
}