import { useState } from "react";
import { Archive, ArrowUpRight, CheckCircle2, FileStack, FolderKanban, KeyRound, MoreHorizontal, Play, Plus, Shield, Users } from "lucide-react";
import { Bar, Chip, Label, Metric, Panel, Shell } from "./_shared/Shell";
import "./_group.css";

type Project = { name: string; team: string; progress: number; budget: string; recent: string; agents: string; status: "active" | "paused" | "archived"; tone: "sky" | "lilac" | "yellow"; memory: string; tools: string; credentials: string; runs: string };

export function Projects() {
  const [filter, setFilter] = useState<"All" | Project["status"]>("All");
  const [selected, setSelected] = useState("Northstar launch");
  const [created, setCreated] = useState(false);
  const [opened, setOpened] = useState(false);
  const [showPolicy, setShowPolicy] = useState(false);
  const projects: Project[] = [
    { name: "Northstar launch", team: "Launch observatory", progress: 68, budget: "$184 / $300", recent: "12 artifacts", agents: "6 agents", status: "active", tone: "sky", memory: "/Projects/Northstar", tools: "web scout · markdown", credentials: "none", runs: "14 this week" },
    { name: "Quiet archive", team: "Memory garden", progress: 42, budget: "$36 / $120", recent: "248 notes", agents: "3 agents", status: "active", tone: "lilac", memory: "/Projects/Archive", tools: "vault search only", credentials: "none", runs: "5 this week" },
    { name: "Q3 ledger", team: "Ledger lantern", progress: 91, budget: "$72 / $100", recent: "6 artifacts", agents: "8 agents", status: "paused", tone: "yellow", memory: "/Projects/Ledger", tools: "CSV + files", credentials: "bank export · scoped", runs: "2 this week" },
  ];
  const current = projects.find(project => project.name === selected) ?? projects[0];
  const visible = projects.filter(project => filter === "All" || project.status === filter);

  return <Shell active="Projects" eyebrow="constellation / project spaces" title="Projects">
    <div className="mb-7 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><Label>isolated spaces</Label><h2 className="mt-2 text-4xl font-extrabold tracking-[-.07em]">Where the work lives.</h2><p className="mt-2 max-w-xl text-sm text-[var(--cyber-muted)]">A project is the permission boundary around agents, tools, credentials, runs, artifacts, approvals, and memory.</p></div><button onClick={() => setCreated(true)} className="flex w-fit items-center gap-2 rounded-xl bg-[var(--cyber-ink)] px-4 py-3 text-xs font-bold text-[var(--cyber-paper)]"><Plus size={15} /> New project</button></div>
    <div className="mb-5 flex items-center gap-2">{(["All", "active", "paused", "archived"] as const).map(item => <button key={item} onClick={() => setFilter(item)} className={`rounded-full px-3 py-2 text-[10px] font-bold capitalize ${filter === item ? "bg-[var(--cyber-ink)] text-[var(--cyber-paper)]" : "bg-[var(--cyber-panel)] text-[var(--cyber-muted)]"}`}>{item} · {item === "All" ? projects.length : projects.filter(project => project.status === item).length}</button>)}</div>
    {created && <Panel className="mb-5 flex flex-wrap items-center justify-between gap-3 border-[#8e70d5] bg-[var(--cyber-lilac)] p-4 text-sm"><span><b>New project draft created.</b> It starts with zero agents, zero credentials, and a proposed memory scope.</span><button onClick={() => setCreated(false)} className="font-bold underline">Dismiss</button></Panel>}
    <div className="grid gap-5 lg:grid-cols-3">{visible.map(project => <Panel key={project.name} className={`overflow-hidden ${selected === project.name ? "ring-2 ring-[#d5c9f3]" : ""}`}><div className="h-2" style={{ background: `var(--cyber-${project.tone})` }} /><div className="p-5"><div className="flex items-start justify-between"><button onClick={() => setSelected(project.name)} aria-label={`Select ${project.name}`} className="grid h-11 w-11 place-items-center rounded-[15px] bg-[var(--cyber-paper)]"><FolderKanban size={19} /></button><button onClick={() => setSelected(project.name)} aria-label={`More actions for ${project.name}`}><MoreHorizontal size={17} /></button></div><button onClick={() => setSelected(project.name)} className="mt-5 text-left"><h3 className="text-xl font-extrabold tracking-[-.04em]">{project.name}</h3><div className="mt-1 text-[11px] text-[var(--cyber-muted)]">{project.team} · {project.status}</div></button><div className="mt-6 flex justify-between text-[10px]"><span>progress</span><b>{project.progress}%</b></div><div className="mt-2"><Bar value={project.progress} color={project.tone === "yellow" ? "#e2b84b" : "#8e70d5"} /></div><div className="mt-5 grid grid-cols-2 gap-2 text-[10px]"><Metric value={project.budget.split(" / ")[0]} label="budget used" tone={project.tone} /><Metric value={project.recent.split(" ")[0]} label={project.recent.split(" ").slice(1).join(" ")} tone="mint" /></div><div className="mt-5 flex items-center gap-2 border-t border-[var(--cyber-line)] pt-4"><Chip tone="mint"><Shield size={10} className="mr-1 inline" /> scoped memory</Chip><span className="text-[10px] text-[var(--cyber-muted)]"><Users size={11} className="mr-1 inline" /> {project.agents}</span></div><button onClick={() => { setSelected(project.name); setOpened(true); }} className="mt-4 w-full rounded-lg border border-[var(--cyber-line)] py-2 text-[11px] font-bold">Open workspace <ArrowUpRight size={13} className="ml-1 inline" /></button></div></Panel>)}</div>
    <Panel className="mt-5 p-5"><div className="flex flex-col justify-between gap-4 border-b border-[var(--cyber-line)] pb-5 md:flex-row md:items-start"><div><Label>selected isolation ledger</Label><h3 className="mt-2 text-2xl font-extrabold tracking-[-.06em]">{current.name}</h3><p className="mt-1 text-[11px] text-[var(--cyber-muted)]">{current.team} · {current.status} · owner Ari Mendez</p></div><div className="flex items-center gap-2">{opened && <Chip tone="mint"><CheckCircle2 size={11} className="mr-1 inline" /> Workspace opened</Chip>}<button onClick={() => setShowPolicy(!showPolicy)} className="rounded-lg border border-[var(--cyber-line)] px-3 py-2 text-[10px] font-bold">{showPolicy ? "Close policy" : "Inspect policy"}</button></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div className="rounded-xl bg-[var(--cyber-paper)] p-3"><Users size={14} /><div className="mt-3 text-[10px] text-[var(--cyber-muted)]">agents</div><b className="mt-1 block text-sm">{current.agents}</b></div><div className="rounded-xl bg-[var(--cyber-paper)] p-3"><WrenchIcon /><div className="mt-3 text-[10px] text-[var(--cyber-muted)]">tools</div><b className="mt-1 block text-[11px]">{current.tools}</b></div><div className="rounded-xl bg-[var(--cyber-paper)] p-3"><KeyRound size={14} /><div className="mt-3 text-[10px] text-[var(--cyber-muted)]">credentials</div><b className="mt-1 block text-[11px]">{current.credentials}</b></div><div className="rounded-xl bg-[var(--cyber-paper)] p-3"><Play size={14} /><div className="mt-3 text-[10px] text-[var(--cyber-muted)]">runs</div><b className="mt-1 block text-[11px]">{current.runs}</b></div><div className="rounded-xl bg-[var(--cyber-paper)] p-3"><FileStack size={14} /><div className="mt-3 text-[10px] text-[var(--cyber-muted)]">memory scope</div><b className="mt-1 block truncate text-[11px]">{current.memory}</b></div></div>{showPolicy && <div className="mt-5 grid gap-3 rounded-xl border border-dashed border-[#c8bfdc] bg-[#fbf9ff] p-4 text-[10px] leading-5 text-[var(--cyber-muted)] md:grid-cols-3"><div><b className="text-[var(--cyber-ink)]">Isolation</b><br />Agents only see assigned project context. Cross-project references become citations.</div><div><b className="text-[var(--cyber-ink)]">Approval</b><br />External writes and new credentials pause at a human gate.</div><div><b className="text-[var(--cyber-ink)]">Memory</b><br />Shared vault search is global; writes are proposed inside this overlay.</div></div>}</Panel>
    <Panel className="mt-5 p-5"><Label>workspace rule</Label><div className="mt-3 flex flex-col gap-3 md:flex-row md:items-center"><Archive size={18} /><p className="flex-1 text-sm text-[var(--cyber-muted)]">Projects are the membrane, not another silo: the common Obsidian brain is searchable, while the project decides which context and proposed writes can cross its edge.</p><button onClick={() => setShowPolicy(true)} className="text-[11px] font-bold underline">Inspect isolation policy</button></div></Panel>
  </Shell>;
}

function WrenchIcon() {
  return <svg aria-hidden="true" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M14.7 6.3a4 4 0 0 0-5.4 5.4L3 18l3 3 6.3-6.3a4 4 0 0 0 5.4-5.4l-2.1 2.1-2.1-2.1 2.2-2.2Z" /></svg>;
}