import { useState } from "react";
import { Check, ChevronDown, Download, ExternalLink, FileCheck2, LockKeyhole, Search, ShieldCheck, Star, Tag, Wrench } from "lucide-react";
import { Chip, Label, Panel, Shell } from "./_shared/Shell";
import "./_group.css";

type Skill = { name: string; desc: string; source: string; trust: string; version: string; update: string; compatibility: string; access: string; scope: string; tone: "sky" | "mint" | "yellow" };

export function SkillLibrary() {
  const [query, setQuery] = useState("");
  const [installed, setInstalled] = useState<string[]>(["Web Scout"]);
  const [filter, setFilter] = useState<"all" | "research" | "memory" | "files">("all");
  const [target, setTarget] = useState("Northstar launch");
  const [openSecurity, setOpenSecurity] = useState<string | null>(null);
  const [showPolicy, setShowPolicy] = useState(false);
  const skills: Skill[] = [
    { name: "Web Scout", desc: "Browse and cite sources without losing the thread.", source: "community / Jun Park", trust: "community reviewed", version: "v2.4.1", update: "current", compatibility: "Mica · research", access: "web · read-only", scope: "project only", tone: "sky" },
    { name: "Markdown Gardener", desc: "Propose tidy frontmatter, backlinks, and safe note edits.", source: "verified / Obsidian team", trust: "verified publisher", version: "v1.8.0", update: "update available", compatibility: "Orbit · Memory wire", access: "vault · proposed write", scope: "choose per project", tone: "mint" },
    { name: "Ledger Lens", desc: "Reconcile CSVs with explainable diffs and a recoverable trail.", source: "private / Ari Mendez", trust: "owner signed", version: "v3.1.2", update: "current", compatibility: "Nix · files", access: "files · scoped", scope: "Ledger lantern", tone: "yellow" },
  ];
  const visible = skills.filter(skill => skill.name.toLowerCase().includes(query.toLowerCase()) || skill.desc.toLowerCase().includes(query.toLowerCase())).filter(skill => filter === "all" || (filter === "research" && skill.name === "Web Scout") || (filter === "memory" && skill.name === "Markdown Gardener") || (filter === "files" && skill.name === "Ledger Lens"));

  const toggleInstall = (name: string) => setInstalled(current => current.includes(name) ? current.filter(item => item !== name) : [...current, name]);

  return <Shell active="Skill library" eyebrow="constellation / skill shelf" title="Skill library">
    <div className="mb-7 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><Label>capabilities with receipts</Label><h2 className="mt-2 text-4xl font-extrabold tracking-[-.07em]">Give the constellation<br />a new trick.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[var(--cyber-muted)]">Skills arrive with a publisher trail, compatibility target, requested permissions, and a project-shaped install boundary.</p></div><div className="relative"><Search className="absolute left-3 top-3 text-[var(--cyber-muted)]" size={15} /><input value={query} onChange={e => setQuery(e.target.value)} className="w-full rounded-xl border border-[var(--cyber-line)] bg-[var(--cyber-panel)] py-3 pl-10 pr-4 text-sm outline-none focus:border-[#8e70d5] lg:w-72" placeholder="Search skills, sources…" /></div></div>
    <div className="mb-5 flex gap-2 overflow-auto">{(["all", "research", "memory", "files"] as const).map(item => <button key={item} onClick={() => setFilter(item)} className={`rounded-full px-3 py-2 text-[10px] font-bold capitalize ${filter === item ? "bg-[var(--cyber-ink)] text-[var(--cyber-paper)]" : "bg-[var(--cyber-panel)] text-[var(--cyber-muted)]"}`}>{item} {item === "all" ? "· 48" : ""}</button>)}<Chip tone="pink">Installed · {installed.length}</Chip></div>
    <Panel className="mb-5 flex flex-col gap-4 p-4 md:flex-row md:items-center"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[var(--cyber-lilac)]"><Wrench size={16} /></div><div className="flex-1"><Label>install target</Label><div className="mt-1 text-sm font-bold">Where should a new skill live?</div></div><select value={target} onChange={e => setTarget(e.target.value)} className="rounded-lg border border-[var(--cyber-line)] bg-[var(--cyber-paper)] px-3 py-2 text-[11px] font-bold outline-none"><option>Northstar launch</option><option>Quiet archive</option><option>Q3 ledger</option></select><span className="text-[10px] text-[var(--cyber-muted)]">Never global</span></Panel>
    <div className="grid gap-5 lg:grid-cols-3">{visible.map(skill => <Panel key={skill.name} className="flex flex-col p-5"><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-[15px]" style={{ background: `var(--cyber-${skill.tone})` }}><Star size={18} /></div><Chip tone={installed.includes(skill.name) ? "mint" : skill.tone}>{installed.includes(skill.name) ? "installed" : skill.version}</Chip></div><h3 className="mt-5 text-lg font-extrabold">{skill.name}</h3><p className="mt-2 min-h-12 text-sm leading-5 text-[var(--cyber-muted)]">{skill.desc}</p><div className="mt-5 space-y-3 border-t border-[var(--cyber-line)] pt-4 text-[10px]"><div className="flex items-start justify-between gap-3"><span className="text-[var(--cyber-muted)]"><Tag size={12} className="mr-1 inline" /> provenance</span><b className="text-right">{skill.source}<br /><span className="font-normal text-[#4c9c76]">{skill.trust}</span></b></div><div className="flex items-start justify-between gap-3"><span className="text-[var(--cyber-muted)]"><ShieldCheck size={12} className="mr-1 inline" /> compatible with</span><b className="text-right">{skill.compatibility}</b></div><div className="flex items-start justify-between gap-3"><span className="text-[var(--cyber-muted)]"><LockKeyhole size={12} className="mr-1 inline" /> requested access</span><b className="text-right">{skill.access}<br /><span className="font-normal text-[var(--cyber-muted)]">{skill.scope}</span></b></div></div><div className="mt-4 flex items-center justify-between rounded-lg bg-[var(--cyber-paper)] p-3 text-[10px]"><span className="flex items-center gap-1"><FileCheck2 size={12} /> {skill.version}</span><span className={skill.update === "update available" ? "font-bold text-[#a35d83]" : "text-[#4c9c76]"}>{skill.update}</span></div><button onClick={() => toggleInstall(skill.name)} className={`mt-5 flex items-center justify-center gap-2 rounded-xl py-3 text-xs font-bold ${installed.includes(skill.name) ? "bg-[var(--cyber-mint)]" : "bg-[var(--cyber-ink)] text-[var(--cyber-paper)]"}`}>{installed.includes(skill.name) ? <><Check size={14} /> Installed to {target}</> : <><Download size={14} /> Install to {target}</>}</button><button onClick={() => setOpenSecurity(openSecurity === skill.name ? null : skill.name)} className="mt-3 text-[10px] font-bold text-[var(--cyber-muted)]"><ExternalLink size={12} className="mr-1 inline" /> {openSecurity === skill.name ? "Hide security notes" : "Read security notes"} <ChevronDown size={11} className="ml-1 inline" /></button>{openSecurity === skill.name && <div className="mt-3 rounded-lg border border-dashed border-[#c8bfdc] bg-[#fbf9ff] p-3 text-[10px] leading-5 text-[var(--cyber-muted)]"><b className="text-[var(--cyber-ink)]">Security review passed.</b><br />No credential access requested. Tool calls are logged and the project scope expires when the run ends.</div>}</Panel>)}</div>
    {visible.length === 0 && <Panel className="p-8 text-center"><Search className="mx-auto text-[var(--cyber-muted)]" size={22} /><h3 className="mt-3 text-sm font-bold">No skill matches that search.</h3><button onClick={() => { setQuery(""); setFilter("all"); }} className="mt-3 text-[11px] font-bold underline">Clear filters</button></Panel>}
    <Panel className="mt-5 flex flex-wrap items-center justify-between gap-3 p-4"><div className="flex items-center gap-3"><div className="grid h-8 w-8 place-items-center rounded-lg bg-[var(--cyber-pink)]"><LockKeyhole size={15} /></div><div><div className="text-sm font-bold">Before activation</div><div className="text-[10px] text-[var(--cyber-muted)]">Review permissions, publisher provenance, and update state. {installed.length} skill{installed.length === 1 ? "" : "s"} installed to {target}.</div></div></div><button onClick={() => setShowPolicy(!showPolicy)} className="text-[11px] font-bold underline">{showPolicy ? "Close install policy" : "View install policy"}</button>{showPolicy && <div className="basis-full rounded-xl bg-[var(--cyber-paper)] p-3 text-[10px] leading-5 text-[var(--cyber-muted)]">Project installs can read only the folders and tools granted by that project. Version updates pause at review until a project owner accepts the changed permission set.</div>}</Panel>
  </Shell>;
}