import { useState } from "react";
import { ChevronDown, CircleCheck, GitBranch, Network, Plus, RotateCcw, Shield, SlidersHorizontal, Users, Wrench, Zap } from "lucide-react";
import { Bar, Chip, Label, Metric, Panel, Shell, Toggle } from "./_shared/Shell";
import "./_group.css";

type Workforce = { name: string; count: string; status: "active" | "paused"; cost: string; load: number; tone: "pink" | "sky" | "yellow"; route: string };

export function Workforces() {
  const [selected, setSelected] = useState("Launch observatory");
  const [filter, setFilter] = useState<"all" | "active" | "paused">("all");
  const [toast, setToast] = useState(false);
  const [showFormation, setShowFormation] = useState(false);
  const [autoRoute, setAutoRoute] = useState(true);
  const [recovery, setRecovery] = useState(true);
  const fleets: Workforce[] = [
    { name: "Launch observatory", count: "6 agents", status: "active", cost: "$24.80", load: 76, tone: "pink", route: "research → brief → approval" },
    { name: "Signal garden", count: "4 agents", status: "active", cost: "$11.40", load: 44, tone: "sky", route: "watch → cluster → cite" },
    { name: "Ledger lantern", count: "8 agents", status: "paused", cost: "$08.62", load: 18, tone: "yellow", route: "parse → reconcile → export" },
  ];
  const visible = fleets.filter(fleet => filter === "all" || fleet.status === filter);
  const current = fleets.find(fleet => fleet.name === selected) ?? fleets[0];
  const workers = [["ORBIT", "chief planner", "full project read", "mint"], ["MICA", "source auditor", "web + read-only", "sky"], ["VALE", "brief writer", "drafts only", "pink"], ["NIX", "checkpoint keeper", "events + artifacts", "yellow"]] as const;

  return <Shell active="Workforces" eyebrow="constellation / workforce studio" title="Workforces">
    <div className="mb-7 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><Label>visual workforce builder</Label><h2 className="mt-2 text-4xl font-extrabold tracking-[-.07em]">Little teams, clear edges.</h2><p className="mt-2 max-w-xl text-sm text-[var(--cyber-muted)]">Every role has an owner, a route, a checkpoint, and somewhere it is not allowed to go.</p></div><button onClick={() => setToast(true)} className="flex w-fit items-center gap-2 rounded-xl bg-[var(--cyber-ink)] px-4 py-3 text-xs font-bold text-[var(--cyber-paper)]"><Plus size={15} /> New workforce</button></div>
    {toast && <div className="mb-5 flex items-center justify-between rounded-xl border border-[#b9a7e9] bg-[var(--cyber-lilac)] p-4 text-[11px]"><span><b>New workforce draft is ready.</b> Assign a role owner before it can receive work.</span><button onClick={() => setToast(false)} className="font-bold underline">Dismiss</button></div>}
    <div className="mb-5 flex flex-wrap items-center gap-2"><Label>show</Label>{(["all", "active", "paused"] as const).map(item => <button key={item} onClick={() => setFilter(item)} className={`rounded-full px-3 py-2 text-[10px] font-bold ${filter === item ? "bg-[var(--cyber-ink)] text-[var(--cyber-paper)]" : "bg-[var(--cyber-panel)] text-[var(--cyber-muted)]"}`}>{item} · {item === "all" ? fleets.length : fleets.filter(f => f.status === item).length}</button>)}<button onClick={() => setShowFormation(!showFormation)} className="ml-auto flex items-center gap-1 text-[10px] font-bold text-[#7659bd]"><SlidersHorizontal size={13} /> {showFormation ? "Hide formation controls" : "Formation controls"}</button></div>
    {showFormation && <Panel className="mb-5 grid gap-4 p-4 md:grid-cols-3"><div><div className="text-[11px] font-bold">Route by load</div><div className="mt-1 text-[10px] text-[var(--cyber-muted)]">Send new tasks to the least busy eligible role.</div></div><div className="flex items-center justify-between rounded-xl bg-[var(--cyber-paper)] p-3 text-[10px]"><span>automatic routing</span><Toggle on={autoRoute} onToggle={() => setAutoRoute(!autoRoute)} label="Automatic routing" /></div><div className="flex items-center justify-between rounded-xl bg-[var(--cyber-paper)] p-3 text-[10px]"><span>checkpoint recovery</span><Toggle on={recovery} onToggle={() => setRecovery(!recovery)} label="Checkpoint recovery" /></div></Panel>}

    <div className="grid gap-5 xl:grid-cols-[.72fr_1.28fr]">
      <Panel className="p-3"><div className="flex items-center justify-between p-3"><Label>my workforces · {fleets.length}</Label><Network size={15} /></div>{visible.map(fleet => <button key={fleet.name} onClick={() => setSelected(fleet.name)} className={`mb-1 w-full rounded-xl p-4 text-left ${selected === fleet.name ? "bg-[var(--cyber-lilac)]" : "hover:bg-[var(--cyber-paper)]"}`}><div className="flex items-start justify-between"><div className="flex gap-3"><div className="grid h-10 w-10 place-items-center rounded-[14px]" style={{ background: `var(--cyber-${fleet.tone})` }}><Users size={17} /></div><div><div className="text-sm font-bold">{fleet.name}</div><div className="mt-1 text-[10px] text-[var(--cyber-muted)]">{fleet.count} · {fleet.status}</div></div></div><span className="mono text-[10px]">{fleet.cost}</span></div><div className="mt-4 flex items-center justify-between text-[9px] text-[var(--cyber-muted)]"><span>route load</span><b className="text-[var(--cyber-ink)]">{fleet.load}%</b></div><div className="mt-1"><Bar value={fleet.load} color={fleet.status === "paused" ? "#e7b54f" : "#8e70d5"} /></div></button>)}</Panel>

      <Panel className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><Label>selected workforce</Label><h3 className="mt-2 text-2xl font-extrabold tracking-[-.06em]">{current.name}</h3><div className="mt-1 flex items-center gap-2 text-[10px] text-[var(--cyber-muted)]"><GitBranch size={12} /> {current.route}</div></div><Chip tone={current.status === "active" ? "mint" : "yellow"}>{current.status === "active" ? "6/6 available" : "paused · recoverable"}</Chip></div>
        <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{workers.map(([agent, role, access, tone]) => <div key={agent} className="rounded-xl border border-[var(--cyber-line)] p-3"><div className="flex items-center gap-2"><div className="grid h-8 w-8 place-items-center rounded-full text-[10px] font-bold" style={{ background: `var(--cyber-${tone})` }}>{agent.slice(0, 2)}</div><div className="text-[11px] font-bold">{agent}<div className="font-normal text-[9px] text-[var(--cyber-muted)]">{role}</div></div></div><div className="mt-3 text-[9px] text-[var(--cyber-muted)]">{access}</div></div>)}</div>
        <div className="mt-6 grid gap-5 md:grid-cols-2"><div><Label>dependencies & checkpoints</Label><div className="mt-3 space-y-2 text-[11px]"><div className="flex items-center gap-2 rounded-lg bg-[var(--cyber-mint)] p-3"><CircleCheck size={14} /><span className="flex-1">source audit</span><b>done</b></div><div className="flex items-center gap-2 rounded-lg bg-[var(--cyber-yellow)] p-3"><CircleCheck size={14} /><span className="flex-1">draft structure</span><b>waiting</b></div><div className="flex items-center gap-2 rounded-lg bg-[var(--cyber-pink)] p-3"><CircleCheck size={14} /><span className="flex-1">external publish</span><b>approval</b></div></div></div><div><Label>tool boundaries</Label><div className="mt-3 rounded-lg bg-[var(--cyber-paper)] p-3 text-[11px]"><div className="flex items-center gap-2"><Wrench size={13} /><span>web search</span><Chip tone="sky">Mica only</Chip></div><div className="mt-3 flex items-center gap-2"><Shield size={13} /><span className="flex-1">vault writes</span><Chip tone="pink">proposed</Chip></div><div className="mt-3 flex items-center gap-2"><Users size={13} /><span className="flex-1">handoffs</span><Chip tone="mint">scoped</Chip></div></div></div></div>
        <div className="mt-6 rounded-xl border border-[var(--cyber-line)] p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-[11px] font-bold"><RotateCcw size={14} /> recovery posture</div><Chip tone="yellow">bounded</Chip></div><div className="mt-4 grid gap-3 text-[10px] sm:grid-cols-3"><Metric value="2" label="retries per task" tone="yellow" /><Metric value="15m" label="idle timeout" tone="sky" /><Metric value="$24.80" label="spent / $40 cap" tone="mint" /></div><div className="mt-4 flex items-center justify-between text-[11px]"><span className="flex items-center gap-2"><Zap size={13} /> checkpoint resume is {recovery ? "on" : "off"}</span><span className="mono text-[9px]">{autoRoute ? "LOAD ROUTING ON" : "MANUAL ROUTING"}</span></div></div>
        <div className="mt-6 flex items-center justify-between border-t border-[var(--cyber-line)] pt-4"><button onClick={() => setShowFormation(!showFormation)} className="text-[11px] font-bold">{showFormation ? "Close formation" : "Edit formation"} <ChevronDown size={13} className="inline" /></button><button onClick={() => setToast(true)} className="rounded-lg bg-[var(--cyber-ink)] px-4 py-2 text-[11px] font-bold text-[var(--cyber-paper)]">{toast ? "Saved locally" : "Save workforce"}</button></div>
      </Panel>
    </div>
  </Shell>;
}