import "./_group.css";
import { ArrowUpRight, BrainCircuit, Check, ChevronRight, Clock3, Cpu, Gauge, Play, ShieldCheck, TriangleAlert, Zap } from "lucide-react";
import { Chip, Meter, Panel, SectionLabel, Shell, Sparkline, Stat } from "./_shared/Shell";

export function Overview() {
  return <Shell active="Overview" title="Operational overview" eyebrow="Tuesday / 21 May 2024">
    <div className="mb-7 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div className="mono text-[10px] uppercase tracking-[.2em] text-[#1479c9]">Good morning, Ari</div><h2 className="mt-2 max-w-2xl text-[clamp(30px,4vw,53px)] font-black leading-[.95] tracking-[-.07em]">Keep the whole<br/><span className="text-[#1479c9]">array in view.</span></h2></div><div className="flex items-center gap-2"><button className="flex items-center gap-2 bg-[#11161b] px-4 py-3 text-[11px] font-bold text-[#e9edf0] hover:bg-[#1479c9]"><Play size={14} fill="currentColor"/> New orchestration</button><button className="border border-[#aeb8bf] bg-[#f7f8f5] px-4 py-3 text-[11px] font-bold hover:bg-[#dcecf8]">Review queue</button></div></div>
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat label="Fleet health" value="94.8%" note="7 of 7 fleets online" trend="0,16 10,14 20,15 30,10 40,11 50,3 60,6 70,2"/><Stat label="Active agents" value="28 / 36" note="8 on standby" trend="0,12 10,14 20,9 30,11 40,5 50,7 60,3 70,4"/><Stat label="Compute window" value="62.4%" note="resets in 04h 18m" trend="0,4 10,6 20,4 30,9 40,8 50,13 60,12 70,17"/><Stat label="Attention" value="03" note="1 elevated · 2 routine"/></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.55fr_1fr]"><Panel className="overflow-hidden"><div className="flex items-center justify-between border-b border-[#c7d0d5] px-5 py-4"><SectionLabel>Live operations</SectionLabel><Chip tone="green">● streaming</Chip></div><div className="grid md:grid-cols-[1.25fr_.75fr]"><div className="border-b border-[#c7d0d5] p-5 md:border-b-0 md:border-r"><div className="flex items-start justify-between"><div><div className="mono text-[9px] uppercase text-[#73808a]">Primary run / R-240521-07</div><h3 className="mt-2 text-[20px] font-black tracking-[-.04em]">Inventory reconciliation</h3><p className="mt-1 text-[11px] text-[#73808a]">Hermes fleet · started 12 min ago · 4 handoffs</p></div><ArrowUpRight size={18} className="text-[#1479c9]"/></div><div className="mt-8 flex items-end justify-between"><div><div className="text-4xl font-black tracking-[-.08em]">68<span className="text-lg text-[#73808a]">%</span></div><div className="mono mt-1 text-[9px] uppercase text-[#73808a]">completion</div></div><Sparkline points="0,18 10,17 20,14 30,15 40,9 50,11 60,4 70,2"/></div><Meter value={68}/><div className="mt-3 flex justify-between mono text-[9px] text-[#73808a]"><span>RETRIEVE SOURCES</span><span>RECONCILE LEDGER</span><span>WRITE REPORT</span></div></div><div className="p-5"><SectionLabel>Agents in run</SectionLabel>{[["ORBIT","lead / planning","active"],["MICA","source audit","active"],["NORTH","ledger diff","waiting"],["VALE","reporting","queued"]].map(([a,b,c],i)=><div key={a} className="flex items-center justify-between border-b border-[#dce2e5] py-3 last:border-0"><div className="flex items-center gap-2"><span className={`grid h-7 w-7 place-items-center text-[9px] font-black ${i===0?"bg-[#11161b] text-[#d5eaff]":"bg-[#dcecf8] text-[#125c94]"}`}>{a.slice(0,2)}</span><div><div className="text-[11px] font-bold">{a}</div><div className="text-[9px] text-[#73808a]">{b}</div></div></div><span className={`mono text-[8px] uppercase ${c==="active"?"text-[#16724e]":"text-[#73808a]"}`}>{c}</span></div>)}</div></div></Panel>
      <div className="space-y-6"><Panel className="p-5"><SectionLabel right={<button className="mono text-[9px] text-[#1479c9]">VIEW ALL</button>}>Needs attention</SectionLabel>{[["TriangleAlert","Credentials expire","OpenClaw / browser token","elevated"],["ShieldCheck","Policy review ready","Memory write scope / 2 items","routine"],["Clock3","Schedule drift","Nightly digest moved +18m","routine"]].map(([icon,title,desc,tone])=><div key={title} className="flex gap-3 border-b border-[#dce2e5] py-3 last:border-0"><div className={`mt-0.5 ${tone==="elevated"?"text-[#c45a4c]":"text-[#1479c9]"}`}>{icon==="TriangleAlert"?<TriangleAlert size={15}/>:icon==="ShieldCheck"?<ShieldCheck size={15}/>:<Clock3 size={15}/>}</div><div className="flex-1"><div className="text-[11px] font-bold">{title}</div><div className="mt-0.5 text-[10px] text-[#73808a]">{desc}</div></div><ChevronRight size={14} className="mt-1 text-[#73808a]"/></div>)}</Panel><Panel className="p-5"><SectionLabel>Next on the desk</SectionLabel><div className="flex gap-3"><div className="mono pt-1 text-[10px] text-[#1479c9]">14:45</div><div><div className="text-[12px] font-bold">Publish morning brief</div><div className="mt-1 text-[10px] text-[#73808a]">OpenClaw / brief-writer · in 13 min</div></div></div><div className="my-4 border-t border-[#dce2e5]"/><div className="flex gap-3"><div className="mono pt-1 text-[10px] text-[#1479c9]">16:00</div><div><div className="text-[12px] font-bold">Fleet health sweep</div><div className="mt-1 text-[10px] text-[#73808a]">All fleets · scheduled check</div></div></div></Panel></div></div>
  </Shell>;
}