// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/agent-os/FleetControl.tsx": () => import("../components/mockups/agent-os/FleetControl.tsx"),
  "./components/mockups/agent-os/MemoryAtlas.tsx": () => import("../components/mockups/agent-os/MemoryAtlas.tsx"),
  "./components/mockups/agent-os/Overview.tsx": () => import("../components/mockups/agent-os/Overview.tsx"),
  "./components/mockups/agent-os/RunConsole.tsx": () => import("../components/mockups/agent-os/RunConsole.tsx")
};
