// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/agent-os/FleetControl.tsx": () => import("../components/mockups/agent-os/FleetControl.tsx"),
  "./components/mockups/agent-os/MemoryAtlas.tsx": () => import("../components/mockups/agent-os/MemoryAtlas.tsx"),
  "./components/mockups/agent-os/Overview.tsx": () => import("../components/mockups/agent-os/Overview.tsx"),
  "./components/mockups/agent-os/RunConsole.tsx": () => import("../components/mockups/agent-os/RunConsole.tsx"),
  "./components/mockups/cyber-array/ChiefAgent.tsx": () => import("../components/mockups/cyber-array/ChiefAgent.tsx"),
  "./components/mockups/cyber-array/Home.tsx": () => import("../components/mockups/cyber-array/Home.tsx"),
  "./components/mockups/cyber-array/MemoryWire.tsx": () => import("../components/mockups/cyber-array/MemoryWire.tsx"),
  "./components/mockups/cyber-array/Projects.tsx": () => import("../components/mockups/cyber-array/Projects.tsx"),
  "./components/mockups/cyber-array/SkillLibrary.tsx": () => import("../components/mockups/cyber-array/SkillLibrary.tsx"),
  "./components/mockups/cyber-array/Workforces.tsx": () => import("../components/mockups/cyber-array/Workforces.tsx")
};
