import { ReactNode, useState } from "react";
import { Activity, Boxes, Brain, Command, FolderKanban, Menu, Network, PackageOpen, ShieldCheck, Sparkles, X } from "lucide-react";
import "../_group.css";

const nav = [
  ["Home", Sparkles], ["Workforces", Network], ["Skill library", PackageOpen],
  ["Projects", FolderKanban], ["Memory wire", Brain], ["Chief agent", ShieldCheck],
] as const;
export function Shell({ active, eyebrow, title, children }: { active:string; eyebrow:string; title:string; children:ReactNode }) {
  const [open,setOpen]=useState(false);
  return <div className="cyber-shell cyber-noise"><aside className={`${open?"translate-x-0":"-translate-x-full"} fixed inset-y-0 left-0 z-30 w-64 border-r border-[var(--cyber-line)] bg-[var(--cyber-panel)] p-5 transition-transform md:translate-x-0`}>
    <div className="flex items-center justify-between border-b border-[var(--cyber-line)] pb-5"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-[13px] bg-[var(--cyber-ink)] text-[var(--cyber-mint)]"><Command size={18}/></div><div><div className="font-extrabold tracking-[-.06em]">CYBER ARRAY</div><div className="mono text-[9px] uppercase tracking-[.16em] text-[var(--cyber-muted)]">personal ops habitat</div></div></div><button className="md:hidden" onClick={()=>setOpen(false)}><X size={16}/></button></div>
    <div className="mono mt-7 text-[9px] uppercase tracking-[.18em] text-[var(--cyber-muted)]">your constellation</div><nav className="mt-3 space-y-1">{nav.map(([label,Icon])=><button key={label} onClick={()=>setOpen(false)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-[12px] font-semibold ${active===label?"bg-[var(--cyber-lilac)] text-[var(--cyber-ink)]":"text-[var(--cyber-muted)] hover:bg-[var(--cyber-paper)]"}`}><Icon size={16}/>{label}<span className="ml-auto text-[10px] opacity-50">›</span></button>)}</nav>
    <div className="absolute bottom-5 left-5 right-5 border-t border-[var(--cyber-line)] pt-4"><div className="flex items-center gap-2 text-[11px] font-semibold"><span className="h-2 w-2 rounded-full bg-[#57bd8b]"/> All systems calm</div><div className="mt-3 flex items-center gap-2 text-[11px] text-[var(--cyber-muted)]"><div className="grid h-7 w-7 place-items-center rounded-lg bg-[var(--cyber-yellow)] text-[10px] font-bold">AM</div>Ari Mendez · owner</div></div>
  </aside>{open&&<button aria-label="close menu" className="fixed inset-0 z-20 bg-[#20263b]/20 md:hidden" onClick={()=>setOpen(false)}/>}<main className="md:pl-64"><header className="flex min-h-[74px] items-center justify-between border-b border-[var(--cyber-line)] bg-[var(--cyber-panel)] px-5 md:px-9"><div className="flex items-center gap-3"><button className="md:hidden" onClick={()=>setOpen(true)}><Menu size={19}/></button><div><div className="mono text-[9px] uppercase tracking-[.2em] text-[var(--cyber-muted)]">{eyebrow}</div><h1 className="mt-1 text-[19px] font-extrabold tracking-[-.04em]">{title}</h1></div></div><div className="hidden items-center gap-4 sm:flex"><div className="flex items-center gap-2 rounded-full bg-[var(--cyber-mint)] px-3 py-2 text-[10px] font-bold"><Activity size={13}/> 7 fleets online</div><div className="mono text-[9px] text-[var(--cyber-muted)]">SYNC 14:32:08</div></div></header><div className="mx-auto max-w-[1500px] p-5 md:p-9">{children}</div></main></div>
}
export function Panel({children,className=""}:{children:ReactNode;className?:string}){return <section className={`rounded-2xl border border-[var(--cyber-line)] bg-[var(--cyber-panel)] shadow-[0_5px_0_rgba(32,38,59,.05)] ${className}`}>{children}</section>}
export function Label({children}:{children:ReactNode}){return <div className="mono text-[9px] font-medium uppercase tracking-[.17em] text-[var(--cyber-muted)]">{children}</div>}
export function Chip({children,tone="sky"}:{children:ReactNode;tone?:string}){const c:any={sky:"bg-[var(--cyber-sky)]",mint:"bg-[var(--cyber-mint)]",pink:"bg-[var(--cyber-pink)]",yellow:"bg-[var(--cyber-yellow)]",lilac:"bg-[var(--cyber-lilac)]"};return <span className={`mono inline-flex rounded-full px-2 py-1 text-[9px] font-medium ${c[tone]||c.sky}`}>{children}</span>}
export function Bar({value,color="var(--cyber-ink)"}:{value:number;color?:string}){return <div className="h-2 overflow-hidden rounded-full bg-[#ebe8e2]"><div className="h-full rounded-full transition-all duration-500" style={{width:`${value}%`,background:color}}/></div>}